# Generated by Django 3.2.17 on 2023-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreviewmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
