# Generated by Django 3.2.17 on 2023-03-01 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewapp', '0002_auto_20230215_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
