# Generated by Django 3.2.17 on 2023-05-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_alter_carreview_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcomment',
            name='car_comment',
        ),
        migrations.AddField(
            model_name='carcomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carcomment',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviewapp.carreview'),
            preserve_default=False,
        ),
    ]
