# Generated by Django 3.2.17 on 2023-08-28 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewapp', '0005_rename_feature_image_carreview_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.RenameField(
            model_name='carreviewmodel',
            old_name='review',
            new_name='review_admin',
        ),
        migrations.RenameModel(
            old_name='CarReview',
            new_name='CarReviewModel',
        ),
        migrations.DeleteModel(
            name='CarComment',
        ),
        migrations.AddField(
            model_name='carcommentmodel',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_user', to='reviewapp.carreviewmodel'),
        ),
    ]
